name: Buff Warp+

on:
  workflow_dispatch:
  push: 
    branches: ['master']
  schedule:
    - cron: '0 0/3 * * *'

jobs:
  Warp:
    name: Buff Warp+
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: buff
        run: |
          chmod +x wp-plus.py
          python wp-plus.py
          